name: user_repository
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mira_api:
    path: ../mira_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:

    path: ../domain_models
  function_and_extension_library:
    path: ../function_and_extension_library
  rxdart: ^0.27.1
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
dev_dependencies:
  flutter_lints: ^4.0.0
