name: mira

publish_to: 'none'
version: 2.0.4+7
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  rxdart: ^0.28.0
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.3.0
  dio: ^5.3.3
  flutter_svg: ^2.0.9
  collection: ^1.18.0
  hive: ^2.0.4
  meta: ^1.9.1
  path_provider: ^2.1.1
  formz: ^0.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  carousel_slider: ^4.2.0


dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.5.4
  build_runner_core: ^7.2.9
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal/Tajawal-Black.ttf
        - asset: fonts/Tajawal/Tajawal-Bold.ttf
        - asset: fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: fonts/Tajawal/Tajawal-Light.ttf
        - asset: fonts/Tajawal/Tajawal-Medium.ttf
        - asset: fonts/Tajawal/Tajawal-Regular.ttf


  assets:
    - assets/
    - assets/icons/
    - assets/location.svg
    - assets/logo.svg
    - assets/logo.png