name: mira_api
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  json_annotation: ^4.7.0


dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.5.4
  build_runner_core: ^7.2.9
  flutter_lints: ^4.0.0
