name: key_value_storage
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  hive: ^2.0.4
  meta: ^1.9.1
  path_provider: ^2.1.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.1.4
  build_runner_core: ^7.2.9
  lints: ^2.1.0
  flutter_lints: ^2.0.3
  