name: function_and_extension_library
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain_models:
    path: ../domain_models
  form_fields:
    path: ../form_fields
  meta: ^1.9.1
  intl: ^0.19.0
  collection: ^1.18.0
dev_dependencies:
  flutter_lints: ^4.0.0
