name: component_library
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  function_and_extension_library:
    path: ../function_and_extension_library
  domain_models:
    path: ../domain_models
  form_fields:
    path: ../form_fields
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  syncfusion_flutter_datepicker: ^25.2.4
  flutter_widget_from_html: ^0.15.1
  collection: ^1.18.0
dev_dependencies:
  flutter_lints: ^4.0.0

